adding more logs

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -47,11 +47,19 @@ jobs:
           chmod 600 ~/.ssh/id_rsa.pub
           
           echo "Adding SSH host to known_hosts"
-          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
+          if ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts 2>&1; then
+            echo "Successfully added SSH host to known_hosts"
+          else
+            echo "Failed to add SSH host to known_hosts"
+            exit 1
+          fi
+          
           chmod 644 ~/.ssh/known_hosts
           
           echo "Contents of known_hosts:"
-          cat ~/.ssh/known_hosts      
+          cat ~/.ssh/known_hosts
+          
+        shell: /usr/bin/bash -e {0}      
       - name: Copy Docker Compose File
         run: |
           scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/docker-compose.yml
